namespace: helm-namespace
buildId: 8 # will be incremented 
web:
  image:
    dockerHubId: houssemdocker
    name: products-store-mvc
    tag: v2.848 # #{Build.BuildId}#
    replicaCount: 1
  port: 80
