apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: sampleapp
spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: sampleapp
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 20
